[channel]
generator = utipod
xmlbase = http://174.93.173.101:8080/UCgkP76aRwL1Kp_62qyQN_lA
description = "Daily options trading insights from Jon and Pete Najarian and the team at Market Rebellion. We share our take on the day’s stock market as viewed through unusual options activity and technical analysis."
title = "Market Rebellion"
link = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA

[channel "image"]
url = https://yt3.googleusercontent.com/ytc/AL5GRJWdOGDjCw5PoZsIQ_Pz08GFJhyfSm1H44kYD_dq=s0

