[item]
guid = -Bmy8Zi6_MU
title = "⏱️60 Seconds $SGFY $AMC $BBBY $GME $WEBR $F $NFLX Rebel's Edge today 1pm 🕐more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=-Bmy8Zi6_MU
category = "Education"
pubdate = Mon, 22 Aug 2022 00:00:00 -0000
enclosure = -Bmy8Zi6_MU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/-Bmy8Zi6_MU/maxresdefault.jpg

