[item]
guid = -szQ5qIyI30
title = "⏱️60 Seconds $WWE $KMX $CRM $COIN $TSLA Rebel's Edge Today 1pm 🕐 #shorts"
description = "#shorts #stockstobuy #stocks #wwe #saudiarabia #options #optionseducation #stmoritz"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=-szQ5qIyI30
category = "Education"
pubdate = Wed, 11 Jan 2023 00:00:00 -0000
enclosure = -szQ5qIyI30.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/-szQ5qIyI30/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYciBJKD0wDw==&rs=AOn4CLDTrD1_ugpq4g8XI-8l6NrQA6yNwg

