[item]
guid = 1AaPQ-Y0XGU
title = "⏱️60 Seconds🌞 $RUN $NOVA $FSLR $SPWR $JBLU $SAVE Rebel's Edge 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=1AaPQ-Y0XGU
category = "Education"
pubdate = Thu, 28 Jul 2022 00:00:00 -0000
enclosure = 1AaPQ-Y0XGU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/1AaPQ-Y0XGU/maxresdefault.jpg

