[item]
guid = 2d0E3I9gEpk
title = "⏱️60 Seconds #FED Day $PARA $CAKE $LTHM $MTCH $EL Rebel's Edge today 🕐1pm  #shorts"
description = "4shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=2d0E3I9gEpk
category = "Education"
pubdate = Wed, 02 Nov 2022 00:00:00 -0000
enclosure = 2d0E3I9gEpk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/2d0E3I9gEpk/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYciA9KDwwDw==&rs=AOn4CLBuqCXERDPd_i-Z3qKII-t3vwhD5Q

