[item]
guid = 2tTmeElivF4
title = "⏱️60 Seconds $RIVN $NIO $BROS $AZN $BMBL Fox with @cvpayne 2pm: Rebel's Edge 1pm more #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=2tTmeElivF4
category = "Education"
pubdate = Thu, 10 Nov 2022 00:00:00 -0000
enclosure = 2tTmeElivF4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/2tTmeElivF4/maxresdefault.jpg

