[item]
guid = 3bPwO11kyQc
title = "⏱️60 Seconds $WFC $C 🏦 $PINS $RIO $BLK $EVTL $UNH more @MarketRebels🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=3bPwO11kyQc
category = "Education"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = 3bPwO11kyQc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/3bPwO11kyQc/maxresdefault.jpg

