[item]
guid = 4Q5Tta80Kec
title = "⏱️60 Seconds $ICCM $GIS $SCS $LCIT Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=4Q5Tta80Kec
category = "Education"
pubdate = Tue, 20 Dec 2022 00:00:00 -0000
enclosure = 4Q5Tta80Kec.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/4Q5Tta80Kec/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYRiBKKHIwDw==&rs=AOn4CLD549wafq2SlHPUE2ZLhErN_qfUCQ

