[item]
guid = 4sI2mZqk8MY
title = "3@3 with Jon Najarian- $SE $FLWS & $EFA"
description = "Ready to start trading? Try Unusual Option Activity Essential. Learn how you can follow the "smart money" with a fresh UOA trade idea each week - including technical levels so that you know where to enter and exit: https://marketrebellion.com/uoa-webinar-1/?utm_source=youtube&utm_medium=marketrebellion\n\nWant more free market intel? Check out Market Rebellion’s Rebel Hub for the biggest stories on market-moving events, how-to trading guides, and the latest in Unusual Option Activity from Jon and Pete Najarian: https://marketrebellion.com/news/?utm_source=youtube&utm_medium=marketrebellion\n\nReady to start trading credit spreads? Try Smart Spreads — credit spread trade ideas crafted by a licensed CMT, using key technical levels, delivered straight to your inbox every week: https://marketrebellion.com/subscriptions/smart-spreads/?utm_source=youtube&utm_medium=marketrebellion"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=4sI2mZqk8MY
category = "Entertainment"
pubdate = Thu, 01 Sep 2022 00:00:00 -0000
enclosure = 4sI2mZqk8MY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/4sI2mZqk8MY/maxresdefault.jpg

