[item]
guid = 4UUnxefs36M
title = "⏱️60 Seconds $CS $HOOD $VSAT $MYOV $VOD $APRN Rebel's Edge at 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=4UUnxefs36M
category = "Education"
pubdate = Mon, 03 Oct 2022 00:00:00 -0000
enclosure = 4UUnxefs36M.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/4UUnxefs36M/maxresdefault.jpg

