[item]
guid = 5tP9hAkpEso
title = "⏱️60 Seconds $GDDY $SKX $OTLY $PNC $MRNA Rebel's Edge today 1pm more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #optionseducation #options #optionstrading #austria #skincare"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=5tP9hAkpEso
category = "Education"
pubdate = Thu, 19 Jan 2023 00:00:00 -0000
enclosure = 5tP9hAkpEso.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/5tP9hAkpEso/maxresdefault.jpg

