[item]
guid = 6jAGp4nzUFw
title = "⏱️60 Seconds #CPI 8.3% 🔥 $AKRO $GETY $ORCL Rebel's Edge 🕐 1pm more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=6jAGp4nzUFw
category = "Education"
pubdate = Tue, 13 Sep 2022 00:00:00 -0000
enclosure = 6jAGp4nzUFw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/6jAGp4nzUFw/maxresdefault.jpg

