[item]
guid = 7Ckohzr4hts
title = "⏱️60 Seconds $VCSA $DIS $BMBL $UTZ $SIX "Rebels Edge" today at 1pm 🕐 more @MarketRebels"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=7Ckohzr4hts
category = "Education"
pubdate = Thu, 11 Aug 2022 00:00:00 -0000
enclosure = 7Ckohzr4hts.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7Ckohzr4hts/maxresdefault.jpg

