[item]
guid = 7KNqBik6eFw
title = "⏱️60 Seconds $BBBY $BBY $BIDU $LCID $MGAM $AVID Rebel's Edge at 1pm🕐 today more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=7KNqBik6eFw
category = "Education"
pubdate = Tue, 30 Aug 2022 00:00:00 -0000
enclosure = 7KNqBik6eFw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7KNqBik6eFw/maxresdefault.jpg

