[item]
guid = 8oxrhCtKVKk
title = "⏱️60 Seconds $SQSP $PHG $JD $TSLA $RYAAY $SIGA $ENVB watch Rebel's Edge with @petenajarian  1pm EST"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=8oxrhCtKVKk
category = "Education"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = 8oxrhCtKVKk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/8oxrhCtKVKk/maxresdefault.jpg

