[item]
guid = 8pkF3wdFrEA
title = "⏱️60 Seconds $SGEN $PFE $UNP $BRK $RC $BRMK Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = "#stocks #shorts #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=8pkF3wdFrEA
category = "Education"
pubdate = Mon, 27 Feb 2023 00:00:00 -0000
enclosure = 8pkF3wdFrEA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/8pkF3wdFrEA/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLDy_zs2BXLbFfyidCxI9XZ4eNuLbg

