[item]
guid = 9AKLfK6izVM
title = "⏱️60 Seconds "Don't be the fish" 🐠 Rebel's Edge today 1pm more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #options #optionseducation #trading #optionstrading #stockstobuy"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=9AKLfK6izVM
category = "Education"
pubdate = Wed, 08 Mar 2023 00:00:00 -0000
enclosure = 9AKLfK6izVM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/9AKLfK6izVM/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYciBKKD8wDw==&rs=AOn4CLDGkd14uUPTpKVdgENH_MyOLiF3ag

