[item]
guid = 9jlw7ty1Udc
title = "⏱️60 Seconds $FTCH $ULTA $EVBG $AFRM $GPS $EA $AMZN Have a great weekend! More @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=9jlw7ty1Udc
category = "Education"
pubdate = Fri, 26 Aug 2022 00:00:00 -0000
enclosure = 9jlw7ty1Udc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/9jlw7ty1Udc/maxresdefault.jpg

