[item]
guid = 9zGfuTvUnQo
title = "🇺🇸60 Seconds $INTC $USB $DOCS $WYNN see you on @3at3_UOA more @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=9zGfuTvUnQo
category = "Education"
pubdate = Fri, 11 Nov 2022 00:00:00 -0000
enclosure = 9zGfuTvUnQo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/9zGfuTvUnQo/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYZSBfKFYwDw==&rs=AOn4CLDFpxp1kh4O4W-Y5Z4NnUKQhWO2Cg

