[item]
guid = _5q67ofsQTE
title = "12k feet before coffee☕️ @CFCstmoritz 🇨🇭 ..BANG!💥 #shorts"
description = "#shorts #switzerland #stmoritz #crypto #finance"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=_5q67ofsQTE
category = "Education"
pubdate = Wed, 11 Jan 2023 00:00:00 -0000
enclosure = _5q67ofsQTE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/_5q67ofsQTE/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYWiBYKGUwDw==&rs=AOn4CLBWFnSxOZmslIh5gunrZP-_SkyUCQ

