[item]
guid = _OzhbI7Kq1Y
title = "⏱️60 Seconds $COST $FDX #OIL 6am #RebelCon2022 workout 🏋️‍♂️more @MarketRebels"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=_OzhbI7Kq1Y
category = "Education"
pubdate = Fri, 23 Sep 2022 00:00:00 -0000
enclosure = _OzhbI7Kq1Y.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/_OzhbI7Kq1Y/maxresdefault.jpg

