[item]
guid = A16XwlA70_M
title = "⏱️60 Seconds #CPI data watch Rebel's Edge today 1pm🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=A16XwlA70_M
category = "Education"
pubdate = Thu, 13 Oct 2022 00:00:00 -0000
enclosure = A16XwlA70_M.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/A16XwlA70_M/maxresdefault.jpg

