[item]
guid = a4bMwDVvwSk
title = "⏱️60 Seconds $ADT $ILMN $BLDP $ECOM $DWAC $BBBY Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=a4bMwDVvwSk
category = "Education"
pubdate = Tue, 06 Sep 2022 00:00:00 -0000
enclosure = a4bMwDVvwSk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/a4bMwDVvwSk/maxresdefault.jpg

