[item]
guid = BaddyACPpW0
title = "⏱️60 Seconds $TSLA $AXP $SI $HAS $INTC 3@3 today #shorts"
description = "#shorts #stockstobuy #options #tsla #tslatrade #optionseducation #optiontrading #miami #miamibeach"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=BaddyACPpW0
category = "Education"
pubdate = Fri, 27 Jan 2023 00:00:00 -0000
enclosure = BaddyACPpW0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/BaddyACPpW0/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYXyBfKF8wDw==&rs=AOn4CLA7i0fxjYo9mkH1jBFMpVNdeqUGEg

