[item]
guid = bk5MJCTlPW4
title = "⏱️60 Seconds $BBBY $SNAP $PVH $CHWY $EXPR more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=bk5MJCTlPW4
category = "Education"
pubdate = Wed, 31 Aug 2022 00:00:00 -0000
enclosure = bk5MJCTlPW4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/bk5MJCTlPW4/maxresdefault.jpg

