[item]
guid = BrIVY_-Imhk
title = "⏱️60 Seconds @ADSK $EOG $SQ $ADBE $CVNA $BYND 3@3 today 🕒 more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=BrIVY_-Imhk
category = "Education"
pubdate = Fri, 24 Feb 2023 00:00:00 -0000
enclosure = BrIVY_-Imhk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/BrIVY_-Imhk/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBNKEIwDw==&rs=AOn4CLCvrvTbZkQxMbmXYGFjahk85c20eA

