[item]
guid = bTA75xr2CgA
title = "⏱️60 Seconds $PDD $JD $XPEV $ZM $WBD $DKS Rebel's Edge at 🕐1pm today more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=bTA75xr2CgA
category = "Education"
pubdate = Tue, 23 Aug 2022 00:00:00 -0000
enclosure = bTA75xr2CgA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/bTA75xr2CgA/maxresdefault.jpg

