[item]
guid = ch2TFvg3HCI
title = "⏱️60 Seconds $TSLA $AAPL $KALA $CALM $LMT $TXT Rebel's Edge today 1pm 🕐 with Pete #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=ch2TFvg3HCI
category = "Education"
pubdate = Fri, 30 Dec 2022 00:00:00 -0000
enclosure = ch2TFvg3HCI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ch2TFvg3HCI/maxresdefault.jpg

