[item]
guid = Ckk_r4_atTc
title = "⏲️60 Seconds $ABNB @MXLESQ $TRIP $ADI $PARA $RBLX Rebel's Edge today 🕐 1pm more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Ckk_r4_atTc
category = "Education"
pubdate = Fri, 17 Feb 2023 00:00:00 -0000
enclosure = Ckk_r4_atTc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Ckk_r4_atTc/maxresdefault.jpg

