[item]
guid = CXwSJOWzkc0
title = "⏱️60 Seconds $NET $BD $DXCM $NWL $LYFT more @MarketRebels 🏴‍☠️ Have a great Super Bowl 🏈weekend"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=CXwSJOWzkc0
category = "Education"
pubdate = Fri, 10 Feb 2023 00:00:00 -0000
enclosure = CXwSJOWzkc0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/CXwSJOWzkc0/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYQyBPKGUwDw==&rs=AOn4CLAeIbxuSE5HW10RZa4eNjUGUb3Biw

