[item]
guid = DN4u24Q4sgE
title = "⏱️60 Seconds $RMED $RGLS $CLVS $CVNA $MSTR Rebel's Edge today 1pm 🕐  from NYSE  @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=DN4u24Q4sgE
category = "Education"
pubdate = Mon, 12 Sep 2022 00:00:00 -0000
enclosure = DN4u24Q4sgE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/DN4u24Q4sgE/maxresdefault.jpg

