[item]
guid = dNT-1iaJMgg
title = "⏱️60 Seconds $POSH $VRM $BIDU $CMCSA $DG Rebels's Edge today 1pm more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=dNT-1iaJMgg
category = "Education"
pubdate = Mon, 15 Aug 2022 00:00:00 -0000
enclosure = dNT-1iaJMgg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/dNT-1iaJMgg/maxresdefault.jpg

