[item]
guid = DqQPIspPjR4
title = "⏱️60 Seconds $WMT $AMZN $HD $PII $MMM $COIN $GM $UBS watch Rebel's Edge 1pm 🕐"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=DqQPIspPjR4
category = "Education"
pubdate = Tue, 26 Jul 2022 00:00:00 -0000
enclosure = DqQPIspPjR4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/DqQPIspPjR4/maxresdefault.jpg

