[item]
guid = dVpJF62e0So
title = "60 Seconds #CPI $WMT $CRM $DIS $BBBY $AAL $LOGI Rebel's Edge today #shorts"
description = "#stocks #shorts #stockstobuy #options #optionseducation #optionstrading #switzerland #stmoritz"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=dVpJF62e0So
category = "Education"
pubdate = Thu, 12 Jan 2023 00:00:00 -0000
enclosure = dVpJF62e0So.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/dVpJF62e0So/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYHCBDKH8wDw==&rs=AOn4CLB9zPF_ulmkJBHhtwEmGZpfHWXtmQ

