[item]
guid = e1zqgwMPQ2s
title = "⏱️ 60 Seconds 2023 1st goal down. Climbing the Hill of Death 💀 "Cerro de la Muerte" 🇵🇷 #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=e1zqgwMPQ2s
category = "Education"
pubdate = Mon, 02 Jan 2023 00:00:00 -0000
enclosure = e1zqgwMPQ2s.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/e1zqgwMPQ2s/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYwCgALgA4oCDAgAEAEYPiBVKHIwDw==&rs=AOn4CLDlIBjtaBxORjXLCVlq6UR8i4xsAw

