[item]
guid = EEi6qh14HuM
title = "⏱️60 Seconds $COWN $ZOOM $PINS $CAT $UBER Rebel's Edge at 1pm🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=EEi6qh14HuM
category = "Education"
pubdate = Tue, 02 Aug 2022 00:00:00 -0000
enclosure = EEi6qh14HuM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/EEi6qh14HuM/maxresdefault.jpg

