[item]
guid = Eg5C3gisTPI
title = "⏱️60 Seconds 🇨🇳 $BABA $JD $BIDU $TME $PCVX $CWEB $PCYX Rebel's Edge at 1pm 🕐 #shorts  🏴‍☠️"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Eg5C3gisTPI
category = "Education"
pubdate = Mon, 24 Oct 2022 00:00:00 -0000
enclosure = Eg5C3gisTPI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Eg5C3gisTPI/sddefault.jpg?sqp=-oaymwEmCIAFEOAD8quKqQMa8AEB-AGGAoAC4AOKAgwIABABGGUgUyhMMA8=&rs=AOn4CLDnuNTTv29cae1-hQY7wvAYTyBWlg

