[item]
guid = eHjttcin9-g
title = "🎭60 Seconds $DASH $DKNG $ROKU $AI $XP more @MarketRebels 🏴‍☠️ Bang 💥"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optiontrading #venice #carnival"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=eHjttcin9-g
category = "Education"
pubdate = Fri, 17 Feb 2023 00:00:00 -0000
enclosure = eHjttcin9-g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/eHjttcin9-g/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBcKFUwDw==&rs=AOn4CLDcBuUTtp1TUnnarJ-AdQrfTUl_ug

