[item]
guid = EIDDdQTdmwQ
title = "⏱️60 Seconds from @Interbourse2023 🇦🇹 $NFLX $GOOG $RL $PD Have a great weekend #shorts"
description = "#shorts #stocks #stockstobuy #options #optionseducation #optionstrading #optionstrategy"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=EIDDdQTdmwQ
category = "Education"
pubdate = Fri, 20 Jan 2023 00:00:00 -0000
enclosure = EIDDdQTdmwQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/EIDDdQTdmwQ/maxresdefault.webp

