[item]
guid = EOP6LKBhiuo
title = "60 Seconds $AAPL China 🇨🇳 $TBLA $FSLR Rebel's Edge at 1pm 🕐 more @MarketRebels 🏴‍☠️#shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=EOP6LKBhiuo
category = "Education"
pubdate = Tue, 29 Nov 2022 00:00:00 -0000
enclosure = EOP6LKBhiuo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/EOP6LKBhiuo/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYciBOKDcwDw==&rs=AOn4CLCA5xTSZyiPoT6UPWjp73sEPV0KjQ

