[item]
guid = EUcc7xk2p3Q
title = "🇪🇸 60 Seconds  from Madrid $BRCM $AAPL $MRVL $ZS $CHPT more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=EUcc7xk2p3Q
category = "Education"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = EUcc7xk2p3Q.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/EUcc7xk2p3Q/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYwCgALgA4oCDAgAEAEYSSBQKGUwDw==&rs=AOn4CLAf_6k8lBFSBUOS131T25n968xpzg

