[item]
guid = F16ZaA-LQaI
title = "⏱️60 Seconds $BRK $ALLY $ZIP $PHG $BHP $WMT Rebel's Edge at 🕐 1pm more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=F16ZaA-LQaI
category = "Education"
pubdate = Tue, 16 Aug 2022 00:00:00 -0000
enclosure = F16ZaA-LQaI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/F16ZaA-LQaI/maxresdefault.jpg

