[item]
guid = FCStgZpyRf8
title = "⏱️60 Seconds $SBMB $JNJ $SOFI $PFE $UBER $GT $SYK Rebel's Edge today 1pm 🕐 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=FCStgZpyRf8
category = "Education"
pubdate = Tue, 01 Nov 2022 00:00:00 -0000
enclosure = FCStgZpyRf8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/FCStgZpyRf8/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYZSBcKFgwDw==&rs=AOn4CLAwEWE6inLCxInuRrpDPMNlZUB_Wg

