[item]
guid = fm31NlanJic
title = "⏱️60 Seconds $FIS $SRNE $AXSM $GTHX $APRN Rebel's Edge 1pm 🕐 today more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=fm31NlanJic
category = "Education"
pubdate = Mon, 13 Feb 2023 00:00:00 -0000
enclosure = fm31NlanJic.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/fm31NlanJic/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYSyBaKGUwDw==&rs=AOn4CLDM83NnKlzOFXQNiuvkt6om-5vnlg

