[item]
guid = FMmaQoQSesk
title = "⏱️60 Seconds $BKR $BIIB $NFLX $LVS $WYNN $ASML $CALM more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=FMmaQoQSesk
category = "Education"
pubdate = Wed, 20 Jul 2022 00:00:00 -0000
enclosure = FMmaQoQSesk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/FMmaQoQSesk/maxresdefault.jpg

