[item]
guid = FtLFguU1tTw
title = "⏱️60 Seconds $CVAC $IIPR $DFS $RBLX $AA $PLUG Rebel's Edge today 1pm 🕐🏴‍☠️#shorts"
description = "#shorts #austria #saalbach #ski  #options #optionseducation #optionstrading #stockstobuy"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=FtLFguU1tTw
category = "Education"
pubdate = Thu, 19 Jan 2023 00:00:00 -0000
enclosure = FtLFguU1tTw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/FtLFguU1tTw/maxresdefault.webp

