[item]
guid = Gb9InDGIR78
title = "60 Seconds $SNAP $COMS $HCA $ISRG $CLF $VX $AXP more @MarketRebels"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Gb9InDGIR78
category = "Education"
pubdate = Fri, 22 Jul 2022 00:00:00 -0000
enclosure = Gb9InDGIR78.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Gb9InDGIR78/maxresdefault.jpg

