[item]
guid = gizlt1VbRXE
title = "⏱️60 Seconds $FTCH $BBBY $JWN $NERV $WOOF $LZB $INTU more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=gizlt1VbRXE
category = "Education"
pubdate = Wed, 24 Aug 2022 00:00:00 -0000
enclosure = gizlt1VbRXE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/gizlt1VbRXE/maxresdefault.jpg

