[item]
guid = GpIJH8Noe7Q
title = "⏱️60 Seconds $TWLO $PARA more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=GpIJH8Noe7Q
category = "Education"
pubdate = Fri, 17 Feb 2023 00:00:00 -0000
enclosure = GpIJH8Noe7Q.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/GpIJH8Noe7Q/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYUiBlKGMwDw==&rs=AOn4CLDnXrLwYFedpiCtrwdz58SSX4p9rQ

