[item]
guid = I8POWmyQyJ8
title = "⏱️60 Seconds #China 🇨🇳stocks on fire 🔥 $BILI  $PDD $BIDU $BABA $MGM Rebel's Edge today #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=I8POWmyQyJ8
category = "Education"
pubdate = Mon, 05 Dec 2022 00:00:00 -0000
enclosure = I8POWmyQyJ8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/I8POWmyQyJ8/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBSKEwwDw==&rs=AOn4CLCwSvjoO2KaXNfq_AcLuxSs8mMyow

