[item]
guid = IE5HVlHEXkE
title = "⏱️60 Seconds $TSLA $WDAY $ZM $BHP $TGT Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stockstobuy #optionstrading #stocks #optionstradingstrategies"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=IE5HVlHEXkE
category = "Education"
pubdate = Tue, 28 Feb 2023 00:00:00 -0000
enclosure = IE5HVlHEXkE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/IE5HVlHEXkE/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBeKFUwDw==&rs=AOn4CLBbrPHfkE_ZGHwD62AMhu0dcl8FaA

