[item]
guid = iEZcWxEp9w0
title = "⏱️60 Seconds $COIN $CRM $INTC $TSLA see you 2:15pm with @cvpayne FOX more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #stockmarket #options #optionseducation #optiontrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=iEZcWxEp9w0
category = "Education"
pubdate = Mon, 30 Jan 2023 00:00:00 -0000
enclosure = iEZcWxEp9w0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/iEZcWxEp9w0/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYTSBXKGUwDw==&rs=AOn4CLAfeSMfPWPvnIkXs8w36NtPgOFJiA

