[item]
guid = ifCRVfVcO-c
title = "⏱️60 Seconds $WMT $HD $MDT Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=ifCRVfVcO-c
category = "Education"
pubdate = Tue, 21 Feb 2023 00:00:00 -0000
enclosure = ifCRVfVcO-c.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ifCRVfVcO-c/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYZiBmKGYwDw==&rs=AOn4CLALsUGqDvim9lAe-j--kWfv-HJpwA

