[item]
guid = iJ6TZhTjKdE
title = "⏱️60 Seconds $EXAS $NKE $MU $RCII $APRN $GNRC more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=iJ6TZhTjKdE
category = "Education"
pubdate = Fri, 30 Sep 2022 00:00:00 -0000
enclosure = iJ6TZhTjKdE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/iJ6TZhTjKdE/maxresdefault.jpg

