[item]
guid = IxhOpx6edwo
title = "⏱️60 Seconds $PD $DASH $ZS $MRVL 3pm @3at3_UOA  more @MarketRebels 🏴‍☠️ #ArtBasel #shorts"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=IxhOpx6edwo
category = "Education"
pubdate = Fri, 02 Dec 2022 00:00:00 -0000
enclosure = IxhOpx6edwo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/IxhOpx6edwo/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBiKFcwDw==&rs=AOn4CLChVczvyWZFZUb4fjDARlN9uqCvEA

