[item]
guid = JF1NsCJIEvs
title = "⏱️60 Seconds $TWTR $XOM $CVX $AMZN $AAPL $PINS more @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=JF1NsCJIEvs
category = "Education"
pubdate = Fri, 28 Oct 2022 00:00:00 -0000
enclosure = JF1NsCJIEvs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/JF1NsCJIEvs/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYYCgALgA4oCDAgAEAEYEyBGKH8wDw==&rs=AOn4CLC-wxq8T7K79ELGT7Cxivzj0pGWAg

