[item]
guid = jKhMzvobrD0
title = "⏱️60 Seconds $AAPL $META $DASh $OUST $VLDR Rebel's Edge at 1pm today 🕐 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=jKhMzvobrD0
category = "Education"
pubdate = Mon, 07 Nov 2022 00:00:00 -0000
enclosure = jKhMzvobrD0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/jKhMzvobrD0/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLBSdFd47cLMvOYVpUCmlKzkhDMxCw

