[item]
guid = jX56vwQoVKY
title = "⏱️60 Seconds $TOPS $DUST $SHFS $TWTR 🚢 $CCL $NCLH more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=jX56vwQoVKY
category = "Education"
pubdate = Wed, 05 Oct 2022 00:00:00 -0000
enclosure = jX56vwQoVKY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/jX56vwQoVKY/maxresdefault.jpg

