[item]
guid = JYL1HAf__XA
title = "⏱️60 Seconds $NVDA $LULU $BRCM $DOCU Rebel's Edge today 1pm more @MarketRebels 🏴‍☠️#shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=JYL1HAf__XA
category = "Education"
pubdate = Fri, 09 Dec 2022 00:00:00 -0000
enclosure = JYL1HAf__XA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/JYL1HAf__XA/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBjKFowDw==&rs=AOn4CLDL9ai2twADLVxYMptYWSGs5fPY6g

