[item]
guid = KfYE-rktyjs
title = "Bizarre things going on in cryptoville. 3@3 at 3pm 🕒 $SL and $MARA activity Friday 3/10  $5.50 puts"
description = "#shorts #crypto"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=KfYE-rktyjs
category = "Education"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = KfYE-rktyjs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/KfYE-rktyjs/hq2.jpg

