[item]
guid = KlYQlYQ3Z1g
title = "⏱️60 Seconds $MARA $RIOT $COIN $UNG $SBSW on  @FoxBusiness with @cvpayne #shorts"
description = "#shorts #stocks #options #optionseducation #optionstrading #stockstobuy @FoxBusiness #charlespayne #unusualactivity"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=KlYQlYQ3Z1g
category = "Education"
pubdate = Tue, 17 Jan 2023 00:00:00 -0000
enclosure = KlYQlYQ3Z1g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/KlYQlYQ3Z1g/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYQiBPKGUwDw==&rs=AOn4CLB8rTQsV3MsEGOkeB8D0n7wc9v9GA

