[item]
guid = KsfruBikJU8
title = "⏱️60 Seconds $META $TDOC $PTEn $HON $CAT $SNBR Rebel's Edge today 1pm 🕐more @MarketRebels 🏴‍☠️"
description = "#shorts @JonNajarian"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=KsfruBikJU8
category = "Education"
pubdate = Thu, 27 Oct 2022 00:00:00 -0000
enclosure = KsfruBikJU8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/KsfruBikJU8/maxresdefault.webp

