[item]
guid = kwXrwu3mGWM
title = "⏱️60 Seconds $RAD $NKE $FDX $SIX $SBUX Market Rebel's today 1pm more @MarketRebels 🏴‍☠️#shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=kwXrwu3mGWM
category = "Education"
pubdate = Wed, 21 Dec 2022 00:00:00 -0000
enclosure = kwXrwu3mGWM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/kwXrwu3mGWM/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYPCBcKHIwDw==&rs=AOn4CLBdkkTpLgIVJFqu6RK4qvBke6WdUg

