[item]
guid = L2Bx88lbHL4
title = "⏱️60 Seconds $LULU $Z $DTC $CINC $TSLA Rebel's Edge 1pm 🕑 more @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts #stocks #stockstobuy #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=L2Bx88lbHL4
category = "Education"
pubdate = Mon, 09 Jan 2023 00:00:00 -0000
enclosure = L2Bx88lbHL4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/L2Bx88lbHL4/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYTyBkKGUwDw==&rs=AOn4CLAXWsZM8oZIOKvP15xryV77e9mW1g

