[item]
guid = lN8LMyzIGMI
title = "[LIVE] 3@3 with Jon Najarian 2023-03-03 15:19"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=lN8LMyzIGMI
category = "Entertainment"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = lN8LMyzIGMI.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/lN8LMyzIGMI/maxresdefault_live.jpg

