[item]
guid = LNvwMbyMb9M
title = "⏱️60 Seconds $LOW $TGT $TJX $DNUT 🍩 $MANU more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=LNvwMbyMb9M
category = "Education"
pubdate = Wed, 17 Aug 2022 00:00:00 -0000
enclosure = LNvwMbyMb9M.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/LNvwMbyMb9M/maxresdefault.jpg

