[item]
guid = Lp2WojxQG1E
title = "⏱️60 Seconds $WWE $LUV 💔 $CTMX $MRNA $HKD $FATE Tune in 2pm 🕑 @FoxBusiness with @cvpayne #shorts"
description = "#shorts #stockstobuy #stocks  @FoxBusiness"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Lp2WojxQG1E
category = "Education"
pubdate = Fri, 06 Jan 2023 00:00:00 -0000
enclosure = Lp2WojxQG1E.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Lp2WojxQG1E/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBSKFgwDw==&rs=AOn4CLAW-1Fx_DrqWAaWWWyBzCDyFDIdGQ

