[item]
guid = M4EZ56ABMAQ
title = "Day One at #RebelCon Texas more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=M4EZ56ABMAQ
category = "Education"
pubdate = Wed, 21 Sep 2022 00:00:00 -0000
enclosure = M4EZ56ABMAQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/M4EZ56ABMAQ/maxresdefault.jpg

