[item]
guid = MMJ8Px28urg
title = "⏱️60 Seconds $IBM $NCR $HAS $BA $CNK more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=MMJ8Px28urg
category = "Education"
pubdate = Tue, 19 Jul 2022 00:00:00 -0000
enclosure = MMJ8Px28urg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/MMJ8Px28urg/maxresdefault.jpg

