[item]
guid = mTNYbL_zJ1o
title = "🇺🇸60 Seconds  $MDB $SFIX $ABNB $CVNA Rebel's Edge today 1pm more @MarketRebels #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=mTNYbL_zJ1o
category = "Education"
pubdate = Wed, 07 Dec 2022 00:00:00 -0000
enclosure = mTNYbL_zJ1o.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/mTNYbL_zJ1o/maxresdefault.jpg

