[item]
guid = n2NXq45lc4E
title = "⏱️60 Seconds $ADTX $BIAF $BOIL $ALT $PNT $NUE $STLD more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=n2NXq45lc4E
category = "Education"
pubdate = Wed, 14 Sep 2022 00:00:00 -0000
enclosure = n2NXq45lc4E.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/n2NXq45lc4E/maxresdefault.jpg

