[item]
guid = N2t3HX1WOdw
title = "⏰60 Seconds $BBWI $ETSY $EBAY $DG $NVDA @MXLESQ on Rebel’s Edge 1pm 🕐 today"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionstrading #optionseducation"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=N2t3HX1WOdw
category = "Education"
pubdate = Fri, 24 Feb 2023 00:00:00 -0000
enclosure = N2t3HX1WOdw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/N2t3HX1WOdw/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBZKEwwDw==&rs=AOn4CLAGLzoS4zN4ksrH3jQIM1n53fnhAg

