[item]
guid = n4dvdu02S_Q
title = "🕰️ 60 Seconds $META $ALGN $HON $TSLA Rebel’s Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=n4dvdu02S_Q
category = "Education"
pubdate = Fri, 03 Feb 2023 00:00:00 -0000
enclosure = n4dvdu02S_Q.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/n4dvdu02S_Q/maxresdefault.jpg

