[item]
guid = nm4LgvxC5J4
title = "⏱️60 Seconds $OLO $TOST $ILMN $HNST more @MarketRebels 🇫🇷"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=nm4LgvxC5J4
category = "Education"
pubdate = Fri, 12 Aug 2022 00:00:00 -0000
enclosure = nm4LgvxC5J4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/nm4LgvxC5J4/maxresdefault.jpg

