[item]
guid = o7WEQn-tPi8
title = "⏱️60 Seconds $TEVA $PYPL $CMG $GOOGL $MSFT $SHOP $SPOT $BA more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=o7WEQn-tPi8
category = "Education"
pubdate = Wed, 27 Jul 2022 00:00:00 -0000
enclosure = o7WEQn-tPi8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/o7WEQn-tPi8/maxresdefault.jpg

