[item]
guid = oVXCiAPaDZE
title = "⏱️60 Seconds on way to Madrid 🇪🇸 (sorta) $DLTR $SI $CRM Rebel's Edge today 1pm"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=oVXCiAPaDZE
category = "Education"
pubdate = Thu, 02 Mar 2023 00:00:00 -0000
enclosure = oVXCiAPaDZE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/oVXCiAPaDZE/hq2.jpg

