[item]
guid = oZDSVwaViHA
title = "⏱️60 Seconds $CBAC $EURN $ILMN $PRE $OSH $SCH Rebel's Edge today 1pm🕐 #shorts"
description = "#shorts #stocks #stockstobuy #options #optionseducation #optionseducation"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=oZDSVwaViHA
category = "Education"
pubdate = Wed, 11 Jan 2023 00:00:00 -0000
enclosure = oZDSVwaViHA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/oZDSVwaViHA/maxresdefault.jpg

