[item]
guid = PHqnNhRmC74
title = "⏱️60 Seconds $COUP $PATH $NWL $PINS more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=PHqnNhRmC74
category = "Education"
pubdate = Wed, 07 Sep 2022 00:00:00 -0000
enclosure = PHqnNhRmC74.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/PHqnNhRmC74/maxresdefault.jpg

