[item]
guid = PsGc5tWs0u4
title = "⏱️60 Seconds $SPLK $PTON $COMP $TTWO $PRVB Rebel's Edge today 1pm 🕐more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=PsGc5tWs0u4
category = "Education"
pubdate = Thu, 06 Oct 2022 00:00:00 -0000
enclosure = PsGc5tWs0u4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/PsGc5tWs0u4/maxresdefault.jpg

