[item]
guid = pUYwjpmUG5c
title = "⏱️60 Seconds $AMLX $AEO $BILI $PLAY Rebel's Edge at 1pm 🕐 today more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=pUYwjpmUG5c
category = "Education"
pubdate = Thu, 08 Sep 2022 00:00:00 -0000
enclosure = pUYwjpmUG5c.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/pUYwjpmUG5c/maxresdefault.jpg

