[item]
guid = QvpDtN3LGDU
title = "⏱️60 Seconds $PLNT 💪 $DD $LYFT $TRIP $COTY Rebel's Edge at 1pm🕐 today #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=QvpDtN3LGDU
category = "Education"
pubdate = Tue, 08 Nov 2022 00:00:00 -0000
enclosure = QvpDtN3LGDU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/QvpDtN3LGDU/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYciBAKDwwDw==&rs=AOn4CLDA7Vi-S4-isOsmjbJ6gqsAlMgLMA

