[item]
guid = QYkJwmYdlN4
title = "⏱️60 Seconds $TSLA $KMX $DAL $AAL Have a great long weekend! More @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=QYkJwmYdlN4
category = "Education"
pubdate = Fri, 13 Jan 2023 00:00:00 -0000
enclosure = QYkJwmYdlN4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/QYkJwmYdlN4/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBgKFQwDw==&rs=AOn4CLBYrr0fNK5ScckRrra8BfsgKqvYJA

