[item]
guid = rQfTGsEeSDU
title = "⏱️60 Seconds $UAA $HZNP $AMGN $COUP $EAT Rebel's Edge today 1pm #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=rQfTGsEeSDU
category = "Education"
pubdate = Mon, 12 Dec 2022 00:00:00 -0000
enclosure = rQfTGsEeSDU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/rQfTGsEeSDU/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYQCBUKGUwDw==&rs=AOn4CLCKTpryX9X6SGS9cLo0rTu6AKGbfA

