[item]
guid = RRSSDJ_ybfo
title = "⏱️60 Seconds $TSLA $LVS $BX $LUV Rebel's Edge today 🕐1pm more @MarketRebels 🏴‍☠️"
description = "#stocks #shorts #options #optionseducation #optionstrading #optiontrading #stockstobuy #tsla"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=RRSSDJ_ybfo
category = "Education"
pubdate = Thu, 26 Jan 2023 00:00:00 -0000
enclosure = RRSSDJ_ybfo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/RRSSDJ_ybfo/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYRyBPKGUwDw==&rs=AOn4CLAjdirfQKP4dC2rBUg2SBEKglOVPA

