[item]
guid = rwbfDbR5vz4
title = "⏱️60 Seconds $TSLA $AXP $SI $HAS $INTC 3@3 today more @MarketRebels 🏴‍☠️ Have a good weekend"
description = "#shorts #stocks #stockstobuy #stockstowatch #optionseducation #optionseducation #options #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=rwbfDbR5vz4
category = "Education"
pubdate = Fri, 27 Jan 2023 00:00:00 -0000
enclosure = rwbfDbR5vz4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/rwbfDbR5vz4/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYYSBhKGEwDw==&rs=AOn4CLAKDTQXP5KVW3PKTFETECN3b2utOw

