[item]
guid = s2otnyX4zCo
title = "⏱️60 Seconds $CHKP $BA $GPN $BABA $PKI Rebel's Edge today at 1pm 🕐 with @petenajarian"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=s2otnyX4zCo
category = "Education"
pubdate = Mon, 01 Aug 2022 00:00:00 -0000
enclosure = s2otnyX4zCo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/s2otnyX4zCo/maxresdefault.jpg

