[item]
guid = SIW0XGY5z4g
title = "⏱️60 Seconds $NVDA $AMD $MDB $NTNX $OKTA $CIEN $HRL $CPB Rebel's Edge today 🕐 1pm"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=SIW0XGY5z4g
category = "Education"
pubdate = Thu, 01 Sep 2022 00:00:00 -0000
enclosure = SIW0XGY5z4g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/SIW0XGY5z4g/maxresdefault.jpg

