[item]
guid = teHAfFlHwrc
title = "⏱️60 Seconds $GM $KO $XRX $WEBR Rebel's Edge 1pm 🕐 more @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=teHAfFlHwrc
category = "Education"
pubdate = Tue, 25 Oct 2022 00:00:00 -0000
enclosure = teHAfFlHwrc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/teHAfFlHwrc/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYciA-KD4wDw==&rs=AOn4CLDyy3M6LLZOb70b2C1xq6Z-bQpY4g

