[item]
guid = TJOwi9fcjVo
title = "⏱️60 Seconds $CSGP $KEYS $TGT $PANW $STWD Rebel's Edge today 1pm🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=TJOwi9fcjVo
category = "Education"
pubdate = Wed, 22 Feb 2023 00:00:00 -0000
enclosure = TJOwi9fcjVo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/TJOwi9fcjVo/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYQiBQKGUwDw==&rs=AOn4CLBQEgYO-no1yc8ODpTuTvYSVpjlrg

