[item]
guid = U1snjKvV7ZE
title = "⏱️60 Seconds #jobs $LULU $AVGO $SBUX $BBBY $RKLB $BIAF $SHPH have a great labor day weekend..🌞"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=U1snjKvV7ZE
category = "Education"
pubdate = Fri, 02 Sep 2022 00:00:00 -0000
enclosure = U1snjKvV7ZE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/U1snjKvV7ZE/maxresdefault.jpg

