[item]
guid = U_vTG_6Q4lg
title = "⏱️60 Seconds $F $GM $RIVN $TSLA $PG $MRK $AMCR Rebel's Edge 1pm 🕐 today more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=U_vTG_6Q4lg
category = "Education"
pubdate = Mon, 10 Oct 2022 00:00:00 -0000
enclosure = U_vTG_6Q4lg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/U_vTG_6Q4lg/maxresdefault.jpg

