[item]
guid = uhH_pHhtUsI
title = "⏱️60 Seconds AMZN #MEGA Lotto $NVCR $ZLAB $WDC $SI Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=uhH_pHhtUsI
category = "Education"
pubdate = Thu, 05 Jan 2023 00:00:00 -0000
enclosure = uhH_pHhtUsI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/uhH_pHhtUsI/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYViBjKGUwDw==&rs=AOn4CLA0uK1Eh32zUIiXsLm0T_woOmfUCQ

