[item]
guid = uJXPjNCnLKc
title = "⏱️60 Seconds $MANU $ADSK $DE $JWN Rebel's Edge today 1pm 🕐 more👉MarketRebellion.com/edge #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=uJXPjNCnLKc
category = "Education"
pubdate = Wed, 23 Nov 2022 00:00:00 -0000
enclosure = uJXPjNCnLKc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/uJXPjNCnLKc/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYciBOKEAwDw==&rs=AOn4CLARC7igRReUjvwHEB7VGy2jBLl6pw

