[item]
guid = un6N0Qy38Sw
title = "⏱️60 Seconds $MICH $ABNB $SWIR $MRNA $UAA $CVS more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=un6N0Qy38Sw
category = "Education"
pubdate = Wed, 03 Aug 2022 00:00:00 -0000
enclosure = un6N0Qy38Sw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/un6N0Qy38Sw/maxresdefault.jpg

