[item]
guid = UunPfYTrMrU
title = "⏱️60 Seconds $AMD $LULU $BX $LYFT $BBBY watch @3at3_UOA  today 3pm 🕒 🏴‍☠️#shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=UunPfYTrMrU
category = "Education"
pubdate = Tue, 24 Jan 2023 00:00:00 -0000
enclosure = UunPfYTrMrU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/UunPfYTrMrU/maxresdefault.jpg

