[item]
guid = VbCnZzDRULo
title = "⏱60 Seconds $TWTR $PSMT $LEN $AXP $PTON $GPS more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=VbCnZzDRULo
category = "Education"
pubdate = Tue, 12 Jul 2022 00:00:00 -0000
enclosure = VbCnZzDRULo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/VbCnZzDRULo/maxresdefault.jpg

