[item]
guid = vt3-dCmiP3Y
title = "⏱️60 Seconds $XPEV $HZNP $BILI $CRWD $NTAP Rebel's Edge 1pm today 🕐 #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=vt3-dCmiP3Y
category = "Education"
pubdate = Wed, 30 Nov 2022 00:00:00 -0000
enclosure = vt3-dCmiP3Y.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/vt3-dCmiP3Y/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLDTOTcQxuMr6zTPnEpFykKvoBOUSA

