[item]
guid = VU6wJa8BtIw
title = "🇭🇷60 Seconds $AMZN $AAPL $XOM $CVX $INTC more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=VU6wJa8BtIw
category = "Education"
pubdate = Fri, 29 Jul 2022 00:00:00 -0000
enclosure = VU6wJa8BtIw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/VU6wJa8BtIw/maxresdefault.jpg

