[item]
guid = wc7yeMn-o5U
title = "⏱️60 Seconds $LYFT $LVS $PCG $PLNT Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=wc7yeMn-o5U
category = "Education"
pubdate = Mon, 26 Sep 2022 00:00:00 -0000
enclosure = wc7yeMn-o5U.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/wc7yeMn-o5U/maxresdefault.jpg

