[item]
guid = WR9j6cUHA0g
title = "⏱️60 Seconds $META $SPLK $AAPL $BK $BAC $CLR Rebel's Edge 1pm 🕐 today more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=WR9j6cUHA0g
category = "Education"
pubdate = Mon, 17 Oct 2022 00:00:00 -0000
enclosure = WR9j6cUHA0g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/WR9j6cUHA0g/maxresdefault.jpg

