[item]
guid = WzMro9VGIGY
title = "⏱️60 Seconds $BIIB $THO $LYFT $AAPL $DIS $BB Rebel's Edge today 🕐1pm more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=WzMro9VGIGY
category = "Education"
pubdate = Wed, 28 Sep 2022 00:00:00 -0000
enclosure = WzMro9VGIGY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/WzMro9VGIGY/maxresdefault.jpg

