[item]
guid = x0iSX3DlTOE
title = "⏱️60 Seconds $ENR $SPOT $TMUS $PLCE $PYPL $TSN Rebel's Edge and Fox with @cvpayne today Bang💥"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=x0iSX3DlTOE
category = "Education"
pubdate = Mon, 06 Feb 2023 00:00:00 -0000
enclosure = x0iSX3DlTOE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/x0iSX3DlTOE/maxresdefault.webp

