[item]
guid = X3GNmA2Tz7U
title = "⏱️Last 60 second update of 2022!!  $TIGR $HOTH $FUTU $CWEB Happy New Year 🍾 #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=X3GNmA2Tz7U
category = "Education"
pubdate = Fri, 30 Dec 2022 00:00:00 -0000
enclosure = X3GNmA2Tz7U.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/X3GNmA2Tz7U/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYXSBlKDkwDw==&rs=AOn4CLDAFieMZXU4YqeiorTsgqSKgWy6ig

