[item]
guid = xmtwUccFvCA
title = "⏱️60 Seconds $POSH $CS $TSLA $RCKT $FAZE $KALV $GILD Rebel's Edge 1pm 🕐 today  @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=xmtwUccFvCA
category = "Education"
pubdate = Tue, 04 Oct 2022 00:00:00 -0000
enclosure = xmtwUccFvCA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/xmtwUccFvCA/maxresdefault.jpg

