[item]
guid = xO-h6i4NM-E
title = "🎂 60 Seconds $AAPL $KMX $OXY $JEF $MTN Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=xO-h6i4NM-E
category = "Education"
pubdate = Thu, 29 Sep 2022 00:00:00 -0000
enclosure = xO-h6i4NM-E.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/xO-h6i4NM-E/maxresdefault.jpg

