[item]
guid = xrfiyUK63D4
title = "60 Seconds from Miami 🏝️ #shorts"
description = "#shorts #options #optionseducation #optionstrading #optiontrading #stocks #stockstobuy"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=xrfiyUK63D4
category = "Education"
pubdate = Wed, 25 Jan 2023 00:00:00 -0000
enclosure = xrfiyUK63D4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/xrfiyUK63D4/maxresdefault.jpg

