[item]
guid = Xz-mBWp7ILM
title = "⏱️60 Seconds $KALA $HOTh $GRRR $LI $PBR $COTY Rebel's Edge today 1pm 🕐 🏴‍☠️#shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Xz-mBWp7ILM
category = "Education"
pubdate = Tue, 03 Jan 2023 00:00:00 -0000
enclosure = Xz-mBWp7ILM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Xz-mBWp7ILM/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYYCBlKEAwDw==&rs=AOn4CLCk7XDsW8Uje6jevTp0miz3zaa1AA

