[item]
guid = YCisfeyJ1s4
title = "⏱️60 Seconds $GS $SYF $BAC $COIN $TWTR $PARA Rebels Edge at 12:30 @MarketRebels 🏴‍☠️ for more info"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=YCisfeyJ1s4
category = "Education"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = YCisfeyJ1s4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/YCisfeyJ1s4/maxresdefault.jpg

