[item]
guid = Yl5w2x3W-L4
title = "⏱️60 Seconds $NFLX $JWN $DHR $UNP $CSX $NSC $ARNC Rebel's Edge at 🕐 1pm more @MarketRebels 🏴‍☠️"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Yl5w2x3W-L4
category = "Education"
pubdate = Thu, 15 Sep 2022 00:00:00 -0000
enclosure = Yl5w2x3W-L4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Yl5w2x3W-L4/maxresdefault.jpg

