[item]
guid = ywgZJaogIS4
title = "⏱️60 Seconds $INMN $DOCU $ZS $COIN $ZUMZ $IDEX see you on @HalftimeReport Noon with @TheDomino"
description = ""
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=ywgZJaogIS4
category = "Education"
pubdate = Fri, 09 Sep 2022 00:00:00 -0000
enclosure = ywgZJaogIS4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ywgZJaogIS4/maxresdefault.jpg

