[item]
guid = zHjHjvHMGEQ
title = "⏱️60 Seconds $LCID $TSLA $PFE $CAT $F $GM Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stockstobuy #stocks #options #optionseducation #optionstrading #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=zHjHjvHMGEQ
category = "Education"
pubdate = Tue, 31 Jan 2023 00:00:00 -0000
enclosure = zHjHjvHMGEQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/zHjHjvHMGEQ/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYTyBbKGUwDw==&rs=AOn4CLCUVX6UZWRFgUw51fLMy1WD5_AafA

