[item]
guid = Zpv8J2fhdQ8
title = "⏱️60 Seconds  ⛵️📸 @GRDecter $APPS $AFRM $MAT $CSII $DIS $MGM $MLCO Rebel's Edge today 1pm 🕐"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=Zpv8J2fhdQ8
category = "Education"
pubdate = Thu, 09 Feb 2023 00:00:00 -0000
enclosure = Zpv8J2fhdQ8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Zpv8J2fhdQ8/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYSyBYKGUwDw==&rs=AOn4CLBIQKD-8FYQlloFSARVaxJrmgTPzg

