[item]
guid = zZ0UIv4nTqk
title = "⏱️60 Seconds $PLTR $MSFT $OM $GP $ARKK $COIN Rebel's Edge today 1pm🕐 more @MarketRebels 🏴‍☠️"
description = "#shorts #stocks #stockstobuy #stockstowatch #options #optionseducation #optionstrading"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=zZ0UIv4nTqk
category = "Education"
pubdate = Tue, 14 Feb 2023 00:00:00 -0000
enclosure = zZ0UIv4nTqk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/zZ0UIv4nTqk/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYRCBTKHIwDw==&rs=AOn4CLCPobkJjtag2lCzDwASTMHFep6uoQ

