[item]
guid = ZZshOcMyxWQ
title = "⏱️60 Seconds $GNRC $BILI Rebel's Edge today 1pm 🕐 more @MarketRebels 🏴‍☠️ #shorts"
description = "#shorts"
author = Market Rebellion
source = https://www.youtube.com/channel/UCgkP76aRwL1Kp_62qyQN_lA
link = https://www.youtube.com/watch?v=ZZshOcMyxWQ
category = "Education"
pubdate = Wed, 30 Nov 2022 00:00:00 -0000
enclosure = ZZshOcMyxWQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ZZshOcMyxWQ/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AY4CgALgA4oCDAgAEAEYciBDKD4wDw==&rs=AOn4CLDxs4XW_k7fLYa2QYjli0mOBiA14w

